In [14]:
import pandas as pd

# Load the movie dataset
df = pd.read_csv("../data/movies_sample.csv")

# Show the first 5 rows
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [13]:
# Quick info about columns and data types
df.info()

# Count rows and columns
print("Shape:", df.shape)

# Display column names
print("Columns:", list(df.columns))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movieId       10 non-null     int64
 1   title         10 non-null     object
 2   genres        10 non-null     object
 3   clean_title   10 non-null     object
 4   genres_clean  10 non-null     object
 5   num_genres    10 non-null     int64
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes
Shape: (10, 6)
Columns: ['movieId', 'title', 'genres', 'clean_title', 'genres_clean', 'num_genres']

In [12]:
# See unique genres
print(df["genres"].unique()[:5])

# Count how many unique titles
print("Unique titles:", df["title"].nunique())

# Show 10 random rows
df.sample(10)

['Adventure|Animation|Children|Comedy|Fantasy'
 'Adventure|Children|Fantasy' 'Comedy|Romance' 'Comedy|Drama|Romance'
 'Comedy']
Unique titles: 10

,movieId,title,genres,clean_title,genres_clean,num_genres
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Waiting to Exhale,Comedy Drama Romance,3
6,7,Sabrina (1995),Comedy|Romance,Sabrina,Comedy Romance,2
8,9,Sudden Death (1995),Action,Sudden Death,Action,1
5,6,Heat (1995),Action|Crime|Thriller,Heat,Action Crime Thriller,3
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II,Comedy,1
9,10,GoldenEye (1995),Action|Adventure|Thriller,GoldenEye,Action Adventure Thriller,3
7,8,Tom and Huck (1995),Adventure|Children,Tom and Huck,Adventure Children,2
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Toy Story,Adventure Animation Children Comedy Fantasy,5
1,2,Jumanji (1995),Adventure|Children|Fantasy,Jumanji,Adventure Children Fantasy,3
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men,Comedy Romance,2

In [11]:
# Example: "Toy Story (1995)" → "Toy Story"
df["clean_title"] = df["title"].str.replace(r"\s*\(\d{4}\)$", "", regex=True)

df[["title", "clean_title"]].head()

                                title                  clean_title
0                    Toy Story (1995)                    Toy Story
1                      Jumanji (1995)                      Jumanji
2             Grumpier Old Men (1995)             Grumpier Old Men
3            Waiting to Exhale (1995)            Waiting to Exhale
4  Father of the Bride Part II (1995)  Father of the Bride Part II

In [16]:
# Replace the pipe '|' with spaces
df["genres_clean"] = df["genres"].fillna("").str.replace("|", " ")

# Count number of genres per movie
df["num_genres"] = df["genres"].str.split("|").str.len()

df[["clean_title", "genres_clean", "num_genres"]].head()

KeyError: "['clean_title'] not in index"

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Use the cleaned genre text
tfidf = TfidfVectorizer(token_pattern=r"(?u)\b\w+\b")

# Fit the vectorizer and transform genres into numbers
X = tfidf.fit_transform(df["genres_clean"])

print("Matrix shape:", X.shape)

KeyError: 'genres_clean'